[module]
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.imports]]
path = "github.com/dieulot/instantclick"
[[module.imports.mounts]]
source = "instantclick.js"
target = "assets/jslibs/instantclick/instantclick.js"
